Fix rank_genes_groups_violin when use_raw=False (#1669)
* Fix rank_genes_groups_violin when use_raw=False

Fixes
```
Traceback (most recent call last):
  File "/tmp/tmptq4o33we/job_working_directory/000/50/configs/tmpe21tizb1", line 29, in <module>
    scale='width')
  File "/usr/local/lib/python3.7/site-packages/scanpy/plotting/_tools/__init__.py", line 564, in rank_genes_groups_violin
    df[g] = X_col
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3563, in _set_item
    self._ensure_valid_index(value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3540, in _ensure_valid_index
    value = Series(value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 314, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 729, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional
```

* use get.obs_df as suggested

* remove unused import

* add release note

Co-authored-by: Giovanni Palla <giov.pll@gmail.com>