Exclude matplotlib 3.7 due to incompatibility
matplotlib 3.7 introduces a metaclass incompatibility with scanpy:

      File ".../site-packages/scanpy/plotting/_utils.py", line 35, in <module>
        class _AxesSubplot(Axes, axes.SubplotBase, ABC):
    TypeError: metaclass conflict: the metaclass of a derived class
    must be a (non-strict) subclass of the metaclasses of all its bases

Excluding v3.7 works around this issue.