Pass generated img to plt.coloarbar
This fixes:
```
Traceback (most recent call last):
  File "/private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpn9tl9wf0/job_working_directory/000/2/configs/tmp_r9i0cvx", line 15, in <module>
    sc.pl.dpt_timeseries(
  File "/Users/mvandenb/miniconda3/envs/anndata/lib/python3.8/site-packages/scanpy/plotting/_tools/__init__.py", line 171, in dpt_timeseries
    timeseries_as_heatmap(
  File "/Users/mvandenb/miniconda3/envs/anndata/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 206, in timeseries_as_heatmap
    pl.colorbar(shrink=0.5)
  File "/Users/mvandenb/miniconda3/envs/anndata/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2188, in colorbar
    raise RuntimeError('No mappable was found to use for colorbar '
RuntimeError: No mappable was found to use for colorbar creation. First define a mappable such as an image (with imshow) or a contour set (with contourf).
```
I see that in other places plt.colobar is used in this module you're
doing the same thing. I believe this broke in
https://github.com/theislab/scanpy/commit/64f04d8441d5cfe61da0338312c2742f4ebbff8b.